#!/usr/bin/env python3
"""只消费人工金标准，基于官方 PP-YOLOE-S 人物训练权重继续微调。"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent
sys.path.insert(0, str(HERE))

import config  # noqa: E402
from export_person_detection_coco import export  # noqa: E402


def yaml_path(path: Path) -> str:
    return path.resolve().as_posix()


def write_training_config(epochs: int, batch_size: int, learning_rate: float) -> Path:
    dataset = config.PERSON_DETECTION_COCO_DIR
    output = config.TRAINING_OUTPUT_DIR / "person_detector_checkpoints"
    base = config.PADDLEDETECTION_DIR / "configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml"
    path = dataset / "person_detector.yml"
    # PaddleDetection 2.9 只用字符串是否以 `/` 开头判断 `_BASE_` 是否绝对路径，
    # 因而会误判 Windows 的 `B:/...`。相对路径在两套系统上都能正确解析。
    try:
        base_reference = os.path.relpath(
            base.resolve(), path.parent.resolve()
        ).replace("\\", "/")
    except ValueError:
        # 自定义输出若位于另一盘符，Windows 扩展路径既以 `/` 开头又可被 open() 读取。
        base_reference = f"//?/{yaml_path(base)}"
    content = f"""# Generated by finetune/train_person_detector.py; paths come from finetune/config.py.
_BASE_: ['{base_reference}']
epoch: {epochs}
snapshot_epoch: 1
log_iter: 10
num_classes: 1
export_with_pir: true
save_dir: {yaml_path(output)}
weights: {yaml_path(output / 'model_final')}
pretrain_weights: {yaml_path(config.PERSON_DETECTOR_TRAINING_WEIGHTS)}
LearningRate:
  base_lr: {learning_rate}
  schedulers:
    - !CosineDecay {{max_epochs: {epochs}}}
    - !LinearWarmup {{start_factor: 0.001, epochs: 1}}
TrainReader:
  batch_size: {batch_size}
  worker_num: 12
  # No online augmentation at all; augmentation comes only from offline dust copies.
  # Deterministic preprocessing only: decode -> resize to 640 -> normalize.
  sample_transforms:
    - Decode: {{}}
    - Resize: {{target_size: [640, 640], keep_ratio: False, interp: 2}}
    - NormalizeImage: {{mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}}
    - Permute: {{}}
  batch_transforms:
    - PadGT: {{}}
TrainDataset:
  name: COCODataSet
  image_dir: images
  anno_path: annotations/instances_train.json
  dataset_dir: {yaml_path(dataset)}
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
  allow_empty: true
EvalDataset:
  name: COCODataSet
  image_dir: images
  anno_path: annotations/instances_val.json
  dataset_dir: {yaml_path(dataset)}
  allow_empty: true
TestDataset:
  name: ImageFolder
  anno_path: annotations/instances_val.json
  dataset_dir: {yaml_path(dataset)}
"""
    path.write_text(content, encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description="微调人工金标准人物检测 PP-YOLOE-S")
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--learning-rate", type=float, default=1e-4)
    parser.add_argument("--device", choices=("GPU",), default="GPU")
    parser.add_argument("--resume", type=Path, help="继续此前 PaddleDetection checkpoint")
    parser.add_argument("--prepare-only", action="store_true", help="只导出 COCO 与训练配置")
    args = parser.parse_args()
    if args.epochs < 1 or args.batch_size < 1 or args.learning_rate <= 0:
        raise ValueError("epochs、batch-size 和 learning-rate 必须大于零")
    if not config.PERSON_DETECTOR_TRAINING_WEIGHTS.is_file():
        raise FileNotFoundError(f"缺少官方人物检测训练权重: {config.PERSON_DETECTOR_TRAINING_WEIGHTS}")
    summary = export(config.PERSON_DETECTION_COCO_DIR)
    if not summary["train"][0] or not summary["val"][0]:
        raise ValueError(f"人工金标准训练/验证整图不足: train={summary['train'][0]}, val={summary['val'][0]}")
    training_config = write_training_config(args.epochs, args.batch_size, args.learning_rate)
    print("人物检测人工金标准:", json.dumps(summary, ensure_ascii=False))
    if args.prepare_only:
        print(f"训练配置: {training_config}")
        return 0

    environment = os.environ.copy()
    environment["CUDA_VISIBLE_DEVICES"] = "0"
    # uv 环境中的 CUDA 13 运行库不在默认 DLL 搜索路径，显式补上并修正 Paddle 的探测值。
    nvidia_bin_dirs = [
        config.PROJECT_ROOT / ".venv-train/lib/site-packages/nvidia/cu13/bin/x86_64",
        config.PROJECT_ROOT / ".venv-train/lib/site-packages/nvidia/cudnn/bin",
    ]
    existing = [str(path) for path in nvidia_bin_dirs if path.is_dir()]
    environment["PATH"] = ";".join(existing + [environment.get("PATH", "")])
    if existing:
        environment["FLAGS_win_cuda_bin_dir"] = existing[0]
    use_gpu = "true"
    command = [
        sys.executable, "tools/train.py", "-c", str(training_config),
        "--eval", "-o", f"use_gpu={use_gpu}",
    ]
    command.append("--amp")
    if args.resume:
        command.extend(["--resume", str(args.resume)])
    subprocess.run(command, cwd=config.PADDLEDETECTION_DIR, env=environment, check=True)

    checkpoint = config.TRAINING_OUTPUT_DIR / "person_detector_checkpoints/model_final"
    # 导出走 PIR 静态图 tracing；离线配置为读取旧部署模型设置的
    # FLAGS_enable_pir_api=0 会让 F.sigmoid 收到旧 IR Variable 而失败，
    # 导出前必须显式改回 1（仅移除变量在部分环境下不生效）。
    # 若仍报 sigmoid 错，可手动执行：
    #   env -u FLAGS_enable_pir_api .venv-train/Scripts/python.exe -X utf8 \
    #     vendor/PaddleDetection/tools/export_model.py -c <训练 yml> \
    #     --output_dir models/finetuned -o weights=models/finetuned/person_detector_checkpoints/model_final use_gpu=true
    export_environment = environment.copy()
    export_environment["FLAGS_enable_pir_api"] = "1"
    subprocess.run(
        [
            sys.executable,
            "tools/export_model.py",
            "-c",
            str(training_config),
            "--output_dir",
            str(config.TRAINING_OUTPUT_DIR),
            "-o",
            f"weights={checkpoint}",
            f"use_gpu={use_gpu}",
        ],
        cwd=config.PADDLEDETECTION_DIR,
        env=export_environment,
        check=True,
    )
    generated = config.TRAINING_OUTPUT_DIR / training_config.stem
    target = config.TRAINING_OUTPUT_DIR / "person_detector"
    target.mkdir(parents=True, exist_ok=True)
    model_names = (
        ("model.pdmodel", "model.pdiparams")
        if (generated / "model.pdmodel").is_file()
        else ("model.json", "model.pdiparams")
    )
    for name in model_names:
        source = generated / name
        if not source.is_file():
            raise RuntimeError(f"人物检测部署模型导出不完整: {source}")
        destination = target / name
        if source.resolve() != destination.resolve():
            destination.write_bytes(source.read_bytes())
    print(f"完成: {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
